server:
  port: 8082
 
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
    hostname: localhost
  client: 
    serviceUrl:
      defaultZone: http://localhost:8085/eureka
  
spring:
  application:
    name: cust-service