server:
  port: 8087
  
spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Amit202020/repository1"


#           to check if it's running OK, go to http://localhost:8087/application/default