server:
  port: 8085
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetch-registry: false
    service-url:
      defaultUrl: http://{eureka.instance.hostname}:${server.port}/eureka